version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - APP_STORAGE=${APP_STORAGE}
    ports:
      - ${APP_EXT_PORT}:${APP_PORT}
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4.0
    hostname: mongo_db
    environment:
      - MONGO_INITDB_ROOT_DATABASE=metadata
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
