version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - APP_STORAGE=${APP_STORAGE}
      
    ports:
      - ${APP_EXT_PORT}:${APP_PORT}
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNANE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_EXT_PORT}:${MONGO_PORT}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_EXT_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMIN_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMIN_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASIC_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASIC_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb

