version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - APP_STORAGE=${APP_STORAGE}
    ports:
      - ${APP_EXT_PORT}:${APP_PORT}
